from numpy.core.records import array
from vs import Path

def get_title_video(cls : Path, path : str) -> list: ...

def get_video_characteristics(self, verbose: bool) -> tuple: ...

def write2hdf5(videodata: array, file_name: str, save_video_title: list) -> None: ...

def get_paths(self) -> list: ...

